import type { Metadata } from "next";
import { Noto_Sans_Arabic, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import PopUp from "./_components/PopUp";

const arabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-arabic",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["700", "400"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "حلق نحو مستقبل التجارة عبر إنشاء متجرك الإلكتروني | سلة",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className="custom-scrollbar scroll-smooth sm:bg-none"
    >
      <body
        className={`${arabic.variable} ${poppins.variable} bg-accent-200 sm:bg-white arabic z-[10000] custom-scrollbar relative selection:bg-[rgb(249,241,232)] selection:text-[rgb(249,115,22)]`}
      >
        {/* <Toaster richColors position="top-left" /> */}
        <Toaster
          position="top-left"
          toastOptions={{
            classNames: {
              error: "bg-red-600 text-red-50",
              success: "text-accent-150 bg-accent-white",
              warning: "text-yellow-600 bg-yellow-50",
            },
          }}
        />
        <PopUp />
        <main className="bg-white">{children}</main>
      </body>
    </html>
  );
}
